# Change these first
owner: ccri-ops # Your GitHub organization or username, where this repository lives
repo: system-status-test # The name of this repository

sites:
  - name: Website
    url: https://216.19.113.199
    __dangerous__insecure: true
  #- name: Single Sign-on
  #  url: https://sts.ccri.edu/cas/login
  - name: VPN Client
    url: https://connect2.ccri.edu:10443
    #__dangerous__insecure: true
  #- name: Banner
  #  url: https://admin.ccri.edu/applicationNavigator/actuator/health

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: status.ccri.edu
  baseUrl: /system-status-test
  logoUrl: https://github.com/ccri-ops/system-status/raw/master/assets/CCRI_Logo_White_1in.svg
  themeUrl: https://ccri-ops.github.io/system-status-test/ccri.css
  name: CCRI System Status Test
  introTitle: "System Status & Maintenance"
  introMessage: "Systems and Services are checked every 5 minutes."
  #customBodyHtml: "<center>::CLOUDFLARE_ERROR_500S_BOX::</center>"
  navbar:
    - title: Status
      href: /
    - title: IT Helpdesk
      href: https://ccri.teamdynamix.com/TDClient/Home/

i18n:
  footer: "[CCRI](https://ccri.edu) - This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)"

commitMessages:
  commitAuthorName: "CCRI Upptime Bot"
  commitAuthorEmail: "itops@ccri.edu"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

#non-prod site. use infrequent checks
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/120 * * * *"